version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - run: if [ -e /var/run/docker.sock ]; then sudo chown circleci:circleci /var/run/docker.sock; fi
      - run:
          name: Run Docker
          command: docker run cimg/base:2020.01 echo "hello"