Parameters:
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production
      - Local
      - Integration
      - Test

Mappings:
  DBInstanceTypeMap:
    Production:
      InstanceType: db.m4.medium
      DeleteAutoBckp: true
      MultiAZ: true
      StorageType: io1
    Development:
      InstanceType: db.t3.small
      DeleteAutoBckp: false
      MultiAZ: false
      StorageType: gp2

Conditions:
  IsProduction: !Equals
    - !Ref Environment
    - Production

Resources:
  ServianTechChallengeAppRDSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Servian Tech Challenge App Group
      DBSubnetGroupName: ServianTechChallengeAppDBGroup
      SubnetIds:
        - !ImportValue ServianTechChallengeAppPubSN1
        - !ImportValue ServianTechChallengeAppPubSN2

  ServianTechChallengeAppDBGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress: 
        EC2SecurityGroupId:  !ImportValue ServianTechChallengAppSG
      EC2VpcId: !ImportValue ServianTechChallengAppVPC
      GroupDescription: SG to enable communication from ECS containers to RDS

  ServianTechChallengeAppDBCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 50
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !FindInMap [DBInstanceTypeMap,!Ref 'Environment',InstanceType]
      DBName: app
      DeleteAutomatedBackups: !FindInMap [DBInstanceTypeMap,!Ref 'Environment',DeleteAutoBckp]
      Engine: postgres
      EngineVersion: 12.8
      MasterUsername: postgres #Use SSM 
      MasterUserPassword: changeme #Use SSM
      MaxAllocatedStorage: 100
      MultiAZ: !FindInMap [DBInstanceTypeMap,!Ref 'Environment',MultiAZ]
      PubliclyAccessible: true #Set it to false.
      StorageType: !FindInMap [DBInstanceTypeMap,!Ref 'Environment',StorageType]
      DBSubnetGroupName: !Ref ServianTechChallengeAppRDSubnetGroup
      DBSecurityGroups: 
        - !Ref ServianTechChallengeAppDBGroup
        

Outputs:
  DBInstanceArn:
    Description: DB Instance ARN
    Value: !GetAtt ServianTechChallengeAppDBCluster.Endpoint.Address
    Export:
      Name: ServianTechChallengeAppDBClusterEndpoint

